### ISSUE TITLE
Add jekyll website to covidcaremap.org

### ISSUE THREAD

**Issue by jfrankl** [covidcaremap/covid19-healthsystemcapacity#103]
I am implementing a visual design made by Alex Lash for the COVIDCareMap website. I set this up on a separate repo, temporarily, so it wouldn't conflict with @hectcastro's on #76.
 
Original design: https://share.goabstract.com/a25857d2-832a-43b2-8ded-8fe496cec2aa?mode=design&sha=59f74eb547d1057e22bd48acc9135378c242b3b4
Temporary website repo: https://github.com/jfrankl/covidcaremap-website

Todo:

- [ ] @daveluo needs to update the copy on the site
- [ ] @jfrankl needs to enhance the site to look better on mobile (right now it looks super busted)
- [ ] Someone needs to connect this to the covidcaremap repo and the work @hectcastro is doing on #76 / put it in the right place in the repo

**Comment by hectcastro** [comment]
Happy to take the last task on. I'll leave it up to you all on whether that should happen before or after the copy updates and mobile enhancements. FWIW, I don't anticipate the merge to be too bad since the root of the site in https://github.com/covidcaremap/covid19-healthsystemcapacity/pull/76 retains its Jekyll roots.

**Comment by jfrankl** [comment]
@hectcastro thanks for offering to take that on. That would be great. We should wait until the copy is updated before we publish it, at least, because right now it's lorem ipsum in a lot of places. But if there are ways for you to get started before then, you are welcome to do that.
