### ISSUE TITLE
Clean up erroneous geocoding of facilities

### ISSUE THREAD

**Issue by daveluo** [covidcaremap/covid19-healthsystemcapacity#34]
The geocoding done in https://github.com/daveluo/covid19-healthsystemcapacity/blob/master/nbs/usa_hcris2018_facilitybedcounts_20200313_v1.ipynb is through gmaps/mapbox of the hospital facilities by name, street address, city, state, zipcode. The results are pretty good but there is a handful of what seem like obvious errors (facilities mapped to central America or Europe). 

While we've refactored the notebook in general (in #27), we skipped re-geocoding the facilities so those original errors remain in the produced data and would carry forward as we merge and aggregate more datasets.

We should correct the geolocation of these hospital facility points that are obviously wrong at least in the geojson file that would feed into downstream data processing notebooks (i.e. #32, #30 ). 

There doesn't seem to be that many like this so this could be manually corrected and saved as a new geojson file for the timebeing. Later, we could think about more automated ways to check and correct. In any case, such corrections should be documented in detail (which exact facilities were corrected, through what method) so we can maintain a good record of how the data is manipulated from raw sources to our produced finalized datasets.

**Comment by simonkassel** [comment]
@daveluo yeah, I can do this in part of a PR that addresses #32. Should I tack this on to the end of https://github.com/daveluo/covid19-healthsystemcapacity/blob/master/nbs/usa_hcris2018_facilitybedcounts_20200313_v1.ipynb?

**Comment by lossyrob** [comment]
@simonkassel I'd recommend doing this in a separate notebook that outputs a the `usa_facilities_hcris_geocoded.geojson` in the data folder. That way the `v2` notebook can just use that as is, and we can separate out the geocoding work from the other compilation work for readability.

**Comment by simonkassel** [comment]
i'm a little unclear on where `usa_facilities_hcris_geocoded.geojson` is currently being created? are you saying that you want me to remove erroneous geocoded results from `usa_facilities_hcris_geocoded.geojson` or from `usa_hospital_beds_hcris2018_cleaned3.geojson` the latter seems to have more information

**Comment by lossyrob** [comment]
Sorry, its a bit confusing. The `_geocoded.geonson` was created by me from `_cleaned3.geojson`, so that I could avoid re-geocoding in the v2 hcris notebook. The `_cleaned3.geojson` came from the geocoding section in https://github.com/daveluo/covid19-healthsystemcapacity/blob/master/nbs/usa_hcris2018_facilitybedcounts_20200313_v1.ipynb. You could start from whatever hcris geojson works best - i think having a geocoded dataset (probably containing addresses, which I shouldn't have dropped in the `_geocoded.geojson` file), separate from the version that has all the calculated bed counts keeps things a bit more clean so reprocessing counts doesn't also have to re-geocode. However for now whatever gets us locations of HCRIS facilities with the Provider Number would work
